-- V1__init_schema.sql
-- Version corrigée, portable pour H2 et PostgreSQL.

--
-- Table: users
--
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) DEFAULT '' NOT NULL,
    encrypted_password VARCHAR(255) DEFAULT '' NOT NULL,
    reset_password_token VARCHAR(255),
    reset_password_sent_at TIMESTAMP,
    remember_created_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    admin BOOLEAN DEFAULT FALSE,
    slug VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Index pour la table users
CREATE UNIQUE INDEX index_users_on_id ON users(id);
CREATE UNIQUE INDEX index_users_on_email ON users(email);

--
-- Table: paintings
--
CREATE TABLE paintings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    sell BOOLEAN DEFAULT FALSE,
    slug VARCHAR(255),
    price_cents INTEGER,
    price_currency VARCHAR(255),
    image_url VARCHAR(512),
    thumbnail_url VARCHAR(512),
    technique VARCHAR(255),
    width INTEGER,
    height INTEGER,
    CONSTRAINT pk_paintings PRIMARY KEY (id)
);

-- Index pour la table paintings
CREATE UNIQUE INDEX index_paintings_on_slug ON paintings(id);

--
-- Table: orders
--
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    painting_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    checkout_session_id VARCHAR(255),
    state VARCHAR(255),
    amount_cents INTEGER DEFAULT 0 NOT NULL,
    address VARCHAR(255),
    slug VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- Index pour la table orders
CREATE INDEX index_orders_on_painting_id ON orders(painting_id);
CREATE INDEX index_orders_on_user_id ON orders(user_id);


--
-- Définition des clés étrangères (Foreign Keys)
-- On les ajoute à la fin pour éviter les problèmes de dépendances circulaires.
--

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_on_painting
    FOREIGN KEY (painting_id) REFERENCES paintings(id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_on_user
    FOREIGN KEY (user_id) REFERENCES users(id);
